class bitvector:
    def signed(self) -> int:
        ...
    
class RISCV64:
    def read_register(self, reg: str) -> bitvector|str:
        ...
        
    def read_memory(self, addr: int, width: int = 8) -> int:
        ...
        
    def step_monitor_mem(self) -> list[tuple[str, int, int, int]]:
        ...
    
    def set_verbosity(self, level: int) -> None:
        ...
        
    def write_memory(self, address, value, width=8) -> None:
        ...
        
    def memory_info(self) -> list[tuple[int, int]]:
        ...